export enum TOKENS {
  FETCH_TOKENS_LIST = "FETCH_TOKENS_LIST",
}

export enum QUOTE {
  FETCH_QUOTE = "FETCH_QUOTE",
}

export enum TRANSACTION {
  GET_STATUS = "GET_STATUS",
  HISTORY = "HISTORY",
}
