"use client";

import StatusCard from "@/components/StatusCard/StatusCard";
import TransactionCard from "@/components/TransactionCard/TransactionCard";
import useFetchTransactionStatus from "@/hooks/useFetchTransactionStatus";
import { useAcrossQuoteStore, useTransactionStatusStore } from "@/redux/hooks";

export default function Home() {
  /**
   * txHash is the transaction hash of the deposit transaction
   * currentState is the current state of the transaction
   * deposit is the deposit object returned by across
   */
  const { txHash, currentState, deposit } = useTransactionStatusStore();
  // quote is the quote generated by across
  const { quote } = useAcrossQuoteStore();
  //useFetchTransactionStatus is a custom hook that fetches the status of a transaction
  const { error } = useFetchTransactionStatus(quote?.deposit.originChainId, quote?.deposit.destinationChainId, txHash);

  if (error) {
    console.log("error occured: ", error);
  }

  return (
    <div className="flex justify-center gap-6">
      <TransactionCard />
      {txHash && <StatusCard txHash={txHash} currentState={currentState} deposit={deposit} />}
    </div>
  );
}
